// Daily Activity Report Types

export interface TargetVisitSummary {
  targetId: string;
  targetName: string;
  targetAddress: string;
  visitStatus: "completed" | "skipped" | "in_progress" | "pending";
  arrivalTime?: string;
  departureTime?: string;
  timeSpentMinutes?: number;
  outcome?: string;
  notes?: string;
  leadStatus?: string;
  wasConverted?: boolean;
}

export interface LocationVisit {
  latitude: number;
  longitude: number;
  address?: string;
  timestamp: string;
  durationMinutes?: number;
  type: "check_in" | "target_visit" | "transit" | "break" | "check_out";
}

export interface DailyReport {
  id: string;
  date: string; // YYYY-MM-DD
  userId: string;
  userName: string;
  companyId: string;
  
  // Attendance Summary
  attendance: {
    checkInTime?: string;
    checkOutTime?: string;
    workDurationMinutes?: number;
    lateByMinutes?: number;
    earlyDepartureMinutes?: number;
    status: "present" | "absent" | "half_day" | "on_leave";
  };
  
  // Targets Summary
  targets: {
    total: number;
    visited: number;
    completed: number;
    skipped: number;
    pending: number;
    conversionRate: number; // percentage
    visits: TargetVisitSummary[];
  };
  
  // Location & Travel Summary
  travel: {
    totalDistanceKm: number;
    totalLocationsVisited: number;
    locationUpdates: number;
    firstLocation?: {
      latitude: number;
      longitude: number;
      address?: string;
      timestamp: string;
    };
    lastLocation?: {
      latitude: number;
      longitude: number;
      address?: string;
      timestamp: string;
    };
  };
  
  // Time Distribution
  timeDistribution: {
    travelTimeMinutes: number;
    atTargetsMinutes: number;
    idleTimeMinutes: number;
    breakTimeMinutes: number;
  };
  
  // Leads Summary
  leads: {
    totalInteractions: number;
    newLeads: number;
    followUps: number;
    converted: number;
    notInterested: number;
  };
  
  // Performance Metrics
  performance: {
    targetCompletionRate: number;
    avgTimePerTarget: number;
    punctualityScore: number; // 0-100
    productivityScore: number; // 0-100
  };
  
  // Metadata
  generatedAt: string;
  lastUpdatedAt: string;
  isAutoGenerated: boolean;
  notes?: string;
}

export interface DailyReportFilters {
  startDate?: string;
  endDate?: string;
  userId?: string;
  companyId?: string;
  status?: "present" | "absent" | "all";
}

export interface DailyReportSummary {
  date: string;
  userId: string;
  userName: string;
  status: "present" | "absent" | "half_day" | "on_leave";
  targetsVisited: number;
  targetsCompleted: number;
  distanceKm: number;
  workHours: number;
  productivityScore: number;
}

export interface TeamDailyReport {
  date: string;
  companyId: string;
  totalAgents: number;
  presentAgents: number;
  absentAgents: number;
  totalTargetsVisited: number;
  totalTargetsCompleted: number;
  totalDistanceKm: number;
  avgProductivityScore: number;
  avgWorkHours: number;
  topPerformers: {
    userId: string;
    userName: string;
    score: number;
  }[];
  agentReports: DailyReportSummary[];
}
